name: Rust FP
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt install build-essential libgtk-3-dev nasm
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
